/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PainelIndexRouteImport } from './routes/painel/index'
import { Route as PainelIaRouteImport } from './routes/painel/ia'
import { Route as PainelPlayfakeRouteImport } from './routes/painel/playfake'
import { Route as PainelTelasRouteImport } from './routes/painel/telas'
import { Route as PainelApkRouteImport } from './routes/painel/apk'
import { Route as PainelUsuariosRouteImport } from './routes/painel/usuarios'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as ApiAiImageRouteImport } from './routes/api/ai/image'
import { Route as UserLivescreenUsernameRouteImport } from './routes/user.livescreen.$username'
import { Route as ApiPublicLiveViewUsernameRouteImport } from './routes/api/public/live-view.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelIaRoute = PainelIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => PainelRoute,
} as any)
const PainelPlayfakeRoute = PainelPlayfakeRouteImport.update({
  id: '/playfake',
  path: '/playfake',
  getParentRoute: () => PainelRoute,
} as any)
const PainelTelasRoute = PainelTelasRouteImport.update({
  id: '/telas',
  path: '/telas',
  getParentRoute: () => PainelRoute,
} as any)
const PainelApkRoute = PainelApkRouteImport.update({
  id: '/apk',
  path: '/apk',
  getParentRoute: () => PainelRoute,
} as any)
const PainelUsuariosRoute = PainelUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => PainelRoute,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiImageRoute = ApiAiImageRouteImport.update({
  id: '/api/ai/image',
  path: '/api/ai/image',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLivescreenUsernameRoute = UserLivescreenUsernameRouteImport.update({
  id: '/user/livescreen/$username',
  path: '/user/livescreen/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLiveViewUsernameRoute =
  ApiPublicLiveViewUsernameRouteImport.update({
    id: '/api/public/live-view/$username',
    path: '/api/public/live-view/$username',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteWithChildren
  '/painel/ia': typeof PainelIaRoute
  '/painel/playfake': typeof PainelPlayfakeRoute
  '/painel/telas': typeof PainelTelasRoute
  '/painel/usuarios': typeof PainelUsuariosRoute
  '/painel/': typeof PainelIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/image': typeof ApiAiImageRoute
  '/user/livescreen/$username': typeof UserLivescreenUsernameRoute
  '/api/public/live-view/$username': typeof ApiPublicLiveViewUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/painel/ia': typeof PainelIaRoute
  '/painel/playfake': typeof PainelPlayfakeRoute
  '/painel/telas': typeof PainelTelasRoute
  '/painel/usuarios': typeof PainelUsuariosRoute
  '/painel': typeof PainelIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/image': typeof ApiAiImageRoute
  '/user/livescreen/$username': typeof UserLivescreenUsernameRoute
  '/api/public/live-view/$username': typeof ApiPublicLiveViewUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteWithChildren
  '/painel/ia': typeof PainelIaRoute
  '/painel/playfake': typeof PainelPlayfakeRoute
  '/painel/telas': typeof PainelTelasRoute
  '/painel/usuarios': typeof PainelUsuariosRoute
  '/painel/': typeof PainelIndexRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/image': typeof ApiAiImageRoute
  '/user/livescreen/$username': typeof UserLivescreenUsernameRoute
  '/api/public/live-view/$username': typeof ApiPublicLiveViewUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/painel'
    | '/painel/ia'
    | '/painel/playfake'
    | '/painel/telas'
    | '/painel/usuarios'
    | '/painel/'
    | '/api/ai/chat'
    | '/api/ai/image'
    | '/user/livescreen/$username'
    | '/api/public/live-view/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/painel/ia'
    | '/painel/playfake'
    | '/painel/telas'
    | '/painel/usuarios'
    | '/painel'
    | '/api/ai/chat'
    | '/api/ai/image'
    | '/user/livescreen/$username'
    | '/api/public/live-view/$username'
  id:
    | '__root__'
    | '/'
    | '/painel'
    | '/painel/ia'
    | '/painel/playfake'
    | '/painel/telas'
    | '/painel/usuarios'
    | '/painel/'
    | '/api/ai/chat'
    | '/api/ai/image'
    | '/user/livescreen/$username'
    | '/api/public/live-view/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelRoute: typeof PainelRouteWithChildren
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiImageRoute: typeof ApiAiImageRoute
  UserLivescreenUsernameRoute: typeof UserLivescreenUsernameRoute
  ApiPublicLiveViewUsernameRoute: typeof ApiPublicLiveViewUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/ia': {
      id: '/painel/ia'
      path: '/ia'
      fullPath: '/painel/ia'
      preLoaderRoute: typeof PainelIaRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/playfake': {
      id: '/painel/playfake'
      path: '/playfake'
      fullPath: '/painel/playfake'
      preLoaderRoute: typeof PainelPlayfakeRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/telas': {
      id: '/painel/telas'
      path: '/telas'
      fullPath: '/painel/telas'
      preLoaderRoute: typeof PainelTelasRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/usuarios': {
      id: '/painel/usuarios'
      path: '/usuarios'
      fullPath: '/painel/usuarios'
      preLoaderRoute: typeof PainelUsuariosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/apk': {
      id: '/painel/apk'
      path: '/apk'
      fullPath: '/painel/apk'
      preLoaderRoute: typeof PainelApkRouteImport
      parentRoute: typeof PainelRoute
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/image': {
      id: '/api/ai/image'
      path: '/api/ai/image'
      fullPath: '/api/ai/image'
      preLoaderRoute: typeof ApiAiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/livescreen/$username': {
      id: '/user/livescreen/$username'
      path: '/user/livescreen/$username'
      fullPath: '/user/livescreen/$username'
      preLoaderRoute: typeof UserLivescreenUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live-view/$username': {
      id: '/api/public/live-view/$username'
      path: '/api/public/live-view/$username'
      fullPath: '/api/public/live-view/$username'
      preLoaderRoute: typeof ApiPublicLiveViewUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PainelRouteChildren {
  PainelIaRoute: typeof PainelIaRoute
  PainelPlayfakeRoute: typeof PainelPlayfakeRoute
  PainelTelasRoute: typeof PainelTelasRoute
  PainelApkRoute: typeof PainelApkRoute
  PainelUsuariosRoute: typeof PainelUsuariosRoute
  PainelIndexRoute: typeof PainelIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelIaRoute: PainelIaRoute,
  PainelPlayfakeRoute: PainelPlayfakeRoute,
  PainelTelasRoute: PainelTelasRoute,
  PainelApkRoute: PainelApkRoute,
  PainelUsuariosRoute: PainelUsuariosRoute,
  PainelIndexRoute: PainelIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelRoute: PainelRouteWithChildren,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiImageRoute: ApiAiImageRoute,
  UserLivescreenUsernameRoute: UserLivescreenUsernameRoute,
  ApiPublicLiveViewUsernameRoute: ApiPublicLiveViewUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
